### PR TITLE
Replace ternary expression with standard if-statement in logAndTheta() (so3.hpp)

### PR DESCRIPTION
**Pull request by maren1234**
Hi, I'm new to contributing to open source projects, please give feedback :)

## In short
A small bug fix, where the use of the ternary operator in the function `logAndTheta()` in so3.hpp caused an `incompatible operand types` error when using `atan2` in the expression. 

## What?
I changed the use of the ternary operator, which was added by @Hs293Go in a commit in the PR for Hs293Go:develop (https://github.com/strasdat/Sophus/pull/316/commits/74153be4541291c932278f1664ee179c43c76ea7), to a standard if-else statement (see only commit in PR). 

It seems like `atan2(-n, -w)` returns a different type than `atan2(n, w)` when `Scalar` is of a type `autodiff::dual` (and possibly other more complex types than `float`, `double`, etc). As shown in the error log below, the negative input paramters causes autodiff to use different types in `atan2`, and thus alters its return type.

To overcome this, I used the standard if-else statement. Now, the returned types from `atan2(n, w)` and `atan2(-n, -w)` won't have to be equal (unlike ternary operators) since the returned value is directly cast to the return type `Scalar`.

## Why? 
When using the autodiff library (https://autodiff.github.io/) as the template class to SE3, the code for `logAndTheta()` fails due to the use of the ternary operator. 

**Code snippet that will fail:**
```
Sophus::SE3<autodiff::dual> T;
Eigen::Matrix<autodiff::dual, 6, 1> xi = T.log(); // <-- error upon compilation
```

**Error output from compiler:**
```
{...}

include/sophus/so3.hpp:287:42: error: incompatible operand types ('ArcTan2Expr<autodiff::forward::UnaryExpr<autodiff::forward::NegOp, autodiff::forward::Dual<double, double> &>, autodiff::forward::UnaryExpr<autodiff::forward::NegOp, autodiff::forward::Dual<double, double> &>>' and 'ArcTan2Expr<autodiff::forward::Dual<double, double> &, autodiff::forward::Dual<double, double> &>')
      Scalar atan_nbyw = (w < Scalar(0)) ? atan2(-n, -w) : atan2(n, w);
                                         ^ ~~~~~~~~~~~~~   ~~~~~~~~~~~
include/sophus/se3.hpp:234:34: note: in instantiation of member function 'Sophus::SO3Base<Sophus::SO3<autodiff::forward::Dual<double, double>, 0>>::logAndTheta' requested here
    auto omega_and_theta = so3().logAndTheta();

{...}
```

### Note
I have only observed this bug when using `autodiff::dual` as the template class (described above), but it may well appear for other types.

### CODE REVIEW

**Comment by strasdat** [comment]
@maren1234 please apply formating. I think there is a script in the repo

**Comment by Hs293Go** [comment]
Sophus tests covered usage of the classes under `float`, `double`, and `ceres::Jet`, but never `autodiff::dual`, so I'm not surprised that this bug showed in code from my PR. @strasdat do you see any need to cover `autodiff` datatypes? I might have some time next week to code up a PR to that effect.

@maren1234 The syntax now is heavily inspired another autodiff library, Ceres, viz the `QuaternionToAngleAxis` function inside the `rotation.h` file. I'd appreciate if you could try this syntax.

``` C++
Scalar atan_nbyw = (w < Scalar(0)) ? Scalar(atan2(-n, -w)) : Scalar(atan2(n, w));
```
I'm partial towards the ternary syntax. It is faster than explicit if-else _in theory_ because `atan_nbyw` may be regarded as constant by the compiler during optimization.

**Comment by maren1234** [comment]
@strasdat & @Hs293Go thanks for the feedback. Modified the PR.

**Comment by maren1234** [comment]
@strasdat are there any more scripts I need to run to make the checks successful?

**Comment by strasdat** [comment]
@maren1234, oh, the files in sympy/* folder are auto generated (and there is a regression test for the autogeneration). 

Long story short: If you revert the changes for all files in sympy/*, the tests shall pass.

**Comment by strasdat** [comment]
Closing this and continuing it here: https://github.com/strasdat/Sophus/pull/342

**Pull request closed without merging**
