### PR TITLE
Add missing SOPHUS_FUNC tags to some function definitions

### PR DESCRIPTION
**Pull request by aharmat**
Add missing SOPHUS_FUNC tags to some function definitions. This was preventing their use in CUDA.

### CODE REVIEW

**Comment by strasdat** [comment]
@aharmat, try runnning "./run_format.sh" to fix all the format issues which leads to the CI failures...

**Comment by aharmat** [comment]
@strasdat I don't think that's the problem, running `./run_format.sh` touched a whole bunch of files, but none of them are the ones I updated:
```
aharmat@dell-xps-15:~/Sophus (add_missing_sophus_func)$ ./run_format.sh 
aharmat@dell-xps-15:~/Sophus (add_missing_sophus_func)$ git status
On branch add_missing_sophus_func
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   sympy/cpp_gencode/Se2_Dx_exp_x.cpp
	modified:   sympy/cpp_gencode/Se2_Dx_log_this.cpp
	modified:   sympy/cpp_gencode/Se3_Dx_exp_x.cpp
	modified:   sympy/cpp_gencode/Se3_Dx_log_this.cpp
	modified:   sympy/cpp_gencode/Se3_Dx_this_mul_exp_x_at_0.cpp
	modified:   sympy/cpp_gencode/So2_Dx_log_this.cpp
	modified:   sympy/cpp_gencode/So3_Dx_exp_x.cpp
	modified:   sympy/cpp_gencode/So3_Dx_log_exp_x_times_this_at_0.cpp
	modified:   sympy/cpp_gencode/So3_Dx_log_this.cpp
	modified:   sympy/cpp_gencode/So3_Dx_this_mul_exp_x_at_0.cpp
```

**Comment by strasdat** [comment]
@aharmat, sorry I should have pointed that out explicitly. I believe the run_format.sh script just got fixed in https://github.com/strasdat/Sophus/pull/343 - and hence if you merge master into your branch, it "should" do the formatting correctly.

**Comment by NikolausDemmel** [comment]
> I don't think that's the problem, running ./run_format.sh touched a whole bunch of files, but none of them are the ones I updated:

The reason none of your files where touched is that the run_format.sh script used to only format cpp files. The version on master now also checks header files.

**Pull request closed without merging**
