### PR TITLE
Fix issues with copy assignment

### PR DESCRIPTION
**Pull request by pettni**
Hello,

First of all thanks for creating a very useful library!

This pull request aims to adress two things:
* Issue with assignment from one mapped Lie group to another, i.e.
```c++
Eigen::Map<Sophus::SO2d> m1(p1), m2(p2);
m2 = m1;  // currently this has no effect
```
* Prevent an extra copy when assigning a mapped Lie group to a group type, i.e.
```c++
Eigen::Map<Sophus::SO2d> m1(p1);
Sophus::SO2d copy;
copy = m1;  // currently constructs a temporary Sophus::SO2d that is then assigned to ```copy```
```

# Fixes

I couldn't decide what the best fix is so I implemented two options in ```so3.hpp``` and ```so2.hpp```:

1. Delegate all copy assignment to the base class, as implemented in ```so3.hpp```, and do the CRTP-style assignment in both the default and the templated ```operator=```. This seems to be the intention of the ```SOPHUS_INHERIT_ASSIGNMENT_OPERATORS``` macro. Adding the user-defined ```operator=``` in the base class requires defining constructors that would otherwise be removed,  I made those private to prevent direct instantiation of the base which is undefined behavior with CRTP.

2. Rely on implicitly defined ```operator=``` in the derived type, as implemented in ```so2.hpp```. These will copy-assign the data member when assigning to the same type (e.g. map -> map), and call the base templated ```operator=``` when assiging from a different type (e.g. type -> map) which both have the expected effect.

If you are interested in applying one of these I'll go ahead and implement it uniformly across all the Lie groups.

# Cause of the issue

## ```map -> map``` assignment

The Map specialization uses the macro ```SOPHUS_INHERIT_ASSIGNMENT_OPERATORS(Map)``` that expands to
```c++
using Base::operator =;

Map& operator=(const Map& other) {
  Base::operator=(other);
  return *this;
}

template <typename OtherDerived>
Map& operator=(const DenseBase<OtherDerived>& other) {
  Base::operator=(other.derived());
  return *this;
}
```
The middle non-templated assignment operator is called, which in turn calls e.g. ```SO2Base& operator=(SO2Base const& other) = default;``` but that one does not do any copying in the derived Map type.

## ```map -> type``` assignment

There is no templated copy assignment operator in e.g. ```SO2```, so the copy constructor is called also on assignment which creates an unnecessary intermediate copy.

### CODE REVIEW

**Comment by pettni** [comment]
Seems like there's an issue with the option 1 on clang, where the macro cannot be used outside of Eigen namespaces:

Clang CI link: https://travis-ci.org/github/strasdat/Sophus/jobs/723830077
Eigen macro clang special case: https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/util/Macros.h#L1050

Since option 2 gets rid of macros all together it may be the way to go, though I may be overlooking something.

**Comment by strasdat** [comment]
@pettni thanks, you are awesome! If I understand it correctly, option2 is the cleanest and does not have the "extra copy" overhead either. If you apply this across so{2,3}, se{2,3}, sim{2,3} including unit tests, I most definitely merge it in :)

**Comment by pettni** [comment]
So there’s something I don’t quite get, my understanding was that defining the base constructors as default would have no effect, as they would be implicitly defined anyway. 

However removing them causes a segfault, the weird thing is that it only happens on windows and only for the SO2 group. Since I don’t have a windows machine it’s hard to debug (valgrind on Linux doesn’t turn up any problems).

**Comment by pettni** [comment]
This passes all the CI checks:

https://travis-ci.org/github/strasdat/Sophus/builds/724570049
https://ci.appveyor.com/project/strasdat/sophus/builds/35050390

Is there something else you'd like in order to merge it?

**Comment by strasdat** [comment]
Thanks @pettni that looks like the right solution!

**Pull request merged**
