### PR TITLE
Avoiding side effect in exponential mapping calculation

### PR DESCRIPTION
**Pull request by emanuelev**
Hi guys,

Writing from Imperial College :).

While integrating LSD-SLAM (http://vision.in.tum.de/research/lsdslam) into SLAMBench (http://apt.cs.manchester.ac.uk/projects/PAMELA/tools/SLAMBench/) I ran into this weird issue. When compiling with optimisations disabled, the exponential mapping of SE3Group fails due to some unexpected side effect in the summation. I believe it is coming from a weird interaction between the constant reference to temporary objects and Eigen's operators. 

A possible fix is the one I'm proposing here, but please let me know if there is something that I might be overlooking. I appreciate performance-wise is better to avoid the copy I'm now introducing but hopefully it shouldn't be too penalising.

Bests,

Emanuele

### CODE REVIEW

**Comment by arntanguy** [comment]
I just ran into the same issue, my own unit tests on a project i'm working on started to mysteriously fail. 
Until I realized I had switched to Debug, which is what made the bug appear.

Although I do not really understand what's going on behind the scenes, I can also confirm the effectiveness of the patch, and of the -O3 trick proposed in #14 .


@strasdat could this be checked and merged as soon as possible?

**Comment by emanuelev** [comment]
Just had a look again at this after long time. It was actually the second lvalue reference (Omega*Omega) causing problems so I reverted the first one. Can you please test it again on your machine and see if all the tests pass with -CMAKE_BUILD_TYPE=Debug? Btw I still fully don't understand why this is happening.
Cheers,
Emanuele

**Comment by arntanguy** [comment]
Hi thanks for the update.
I just checked, all unit tests pass both in Release and Debug mode.

**Comment by emanuelev** [comment]
Just did some more experiments. It actually compiles fine with GCC 5 and Clang, pointing to a compiler bug. Since the original code looks absolutely fine, I am not sure if @strasdat or @stevenlovegrove should do anything about this.

**Comment by stevenlovegrove** [comment]
There do look to be some questionable references to temporaries throughout that file. I'm surprised they aren't highlighted as warnings when compiling the tests. Some of the failures in debug may be related to the level of inlining that is or isn't taking place. When I get a chance, I will look further into this.

**Comment by FrancisRussell** [comment]
@emanuelev shared this bug with me. As far as I can tell the const reference to rvalues are all valid. In particular, Valgrind's memcheck has no issues with it, and would certainly catch it if there were invalid reads. 

I also agree this looks like a compiler optimisation bug, In `exp()`, in `se3.hpp`, there's a conditional that's taken dependent on the value of some epsilon. By adding a call to exit() on the path that's *never taken*, I can get the tests to pass.

**Comment by strasdat** [comment]
Okay, I think most of the const reference were not necessary, because of RVO, so I removed them.

Let me close this issue for now.

**Pull request closed without merging**
